[package]
name = "pixelizer"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "*"
rprompt = "*"

[profile.release]
strip = "symbols"
lto = "fat"
codegen-units = 1
opt-level = 3
debug = false
rpath = true